[package]
# Looks for any .java files in the directory recursively
source_dir = "src"
default_repo = "repo url" # Optional. The default repo is maven

[dependencies]
"net.fabricmc.fabric-api:fabric-api" = "0.131.2+1.21.9"

[repos]
# If the package isnt here default repo is maven repos
# Also if it cant find this in the specified repo it will try the maven repo
"net.fabricmc.fabric-api:fabric-api" = "https://maven.fabricmc.net"

# Optional thing to map jars for minecraft
[mapping]
map = "url to mappings jar. must contain mappings.tiny file inside the jar"
# Repos to map
mapped = [
    "https://maven.fabricmc.net/",
    "https://libraries.minecraft.net/"
]
